language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis Server Home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

sciprt: './gradlew clean build'


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webservice-deploy-s3 # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: betterfly88/spring-boot #Github
      branch: master


#CI 실행 완료 후 메일알림
notifications:
  email:
    recipients:
      - betterfly4202@gmail.com