language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis Server Home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

sciprt: './gradlew clean build'

#CI 실행 완료 후 메일알림
notifications:
  email:
    recipients:
      - betterfly4202@gmail.com