spring :
  profiles:
    active : local #기본 환경 선택

---
# local 환경 선택
spring :
  profiles: local
  h2:
      console:
        enabled: true
  datasource :
    data: classpath:data-h2.sql #시작할때 실행시킬 script
    jpa :
      show-sql: true
      hibernate :
        ddl-auto: create-drop
